version: "3.8"

services:
  whatsapp-service:
    build: .
    container_name: whatsapp-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./whatsapp-session:/app/whatsapp-session
      - ./logs:/app/logs
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge
